blog/urls.py
from django.urls import path
from django.conf.urls import url,include

from . import views

app_name='blog'

urlpatterns=[
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('user-auth/', views.user_auth, name='user-auth'),
    path('user-auth/blog/success/', views.success, name='success'),
]

cloudoverview/urls.py
from django.urls import path

from . import views

app_name='cloudoverview'

urlpatterns=[
    path('cloud-overview/', views.cloud_overview, name='cloud-overview'),
    path('create-potential-cloud/', views.PotentialCloudCreateView.as_view(), name='create-potential-cloud'), 
    path('get-potential-cloud-api/', views.get_potential_cloud_api, name='get-potential-cloud-api'), 
    path('delete-potential-cloud/', views.delete_potential_cloud, name='delete-potential-cloud'),
    path('edit-potential-cloud/', views.edit_potential_cloud, name='edit-potential-cloud'),
    path('edit-potential-cloud-modal/', views.get_edit_potential_cloud_modal, name='edit-potential-cloud-modal'),
]

okta/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('utils.urls',namespace='utils')),
    path('',include('demandmanagement.urls',namespace='demandmanagement')),
    path('',include('forecasts.urls',namespace='forecasts')),
    path('',include('cloudoverview.urls',namespace='cloud-overview')),
    path('',include('cloudstats.urls',namespace='cloud-stats')),
    path('',include('resourceaccommodator.urls',namespace='resourceaccommodator')),
]

resourceaccommodator/urls.py
from django.urls import path
from django.conf.urls import url,include

from . import views

app_name='resourceaccommodator'

urlpatterns=[
    path('resource-accommodator/', views.resource_accommodator, name='resource-accommodator'),
    path('resourceaccommodator/cloud-calculator', views.cloud_calculator, name='cloud-calculator'),
    path('get-orderable-item-api/', views.get_orderable_item_api, name='get-orderable-item-api'),
    path('get-all-orderable-items-api', views.get_all_orderable_items_api, name='get-all-orderable-items-api'),
    path('get-all-orderable-items-dtt-api', views.get_all_orderable_items_dtt_api, name='get-all-orderable-items-dtt-api'),
    path('test', views.test, name='test'),
]

cloudoverview/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

class PotentialCloud(models.Model):
    cloud_name = models.CharField(max_length=32, blank=False, null=False, unique=True)
    version = models.CharField(max_length=32, blank=True, null=False)
    number_of_hosts = models.IntegerField(blank=False, null=False)
    cpu_contention = models.FloatField(max_length=32, blank=False, null=False)
    total_cpu = models.FloatField(max_length=32, blank=False, null=False)
    ram_contention = models.FloatField(max_length=32, blank=False, null=False)
    total_ram = models.FloatField(max_length=32, blank=False, null=False)
    storage = models.FloatField(max_length=32, blank=False, null=False)
    provisioning = models.CharField(max_length=32, blank=True)
    
    def save(self, *args, **kwargs):
        return super(PotentialCloud, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.cloud_name)

cloudoverview/forms.py
from .models import PotentialCloud
from bootstrap_modal_forms.forms import BSModalModelForm

class PotentialCloudModelForm(BSModalModelForm):
    class Meta:
        model = PotentialCloud
        fields = ['cloud_name', 'version', 'cpu_contention', 'total_cpu', 'ram_contention', 'total_ram', 'storage', 'number_of_hosts', 'provisioning',]

cloudoverview/views.py
from __future__ import unicode_literals
from django.shortcuts import render,get_object_or_404
from bootstrap_modal_forms.generic import BSModalCreateView
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from .forms import PotentialCloudModelForm
from .models import PotentialCloud
from django.http import JsonResponse
from utils import meteoFunctions
from django.http import HttpResponseRedirect

@login_required(login_url='/')
def cloud_overview(request):
    clouds_info = meteoFunctions.get_clouds_info()
    cloud_capacity_data = meteoFunctions.get_cloud_capacity_data()
    context = {
        "clouds": clouds_info,
        "potential_clouds": PotentialCloud.objects.filter(),
        "cloud_capacity_data": cloud_capacity_data
        }
    
    return render(request, "cloudoverview/cloud-overview.html", context)
   
class PotentialCloudCreateView(BSModalCreateView):
    template_name = 'cloudoverview/create_potential_cloud.html'
    form_class = PotentialCloudModelForm
    success_message = 'Success: Potential Cloud was created.'
    success_url = reverse_lazy('cloudoverview:cloud-overview')

def get_potential_cloud_api(request):
    cloud_name = request.GET.get('potential_cloud')
    potential_cloud = list(PotentialCloud.objects.filter(cloud_name=cloud_name).values())[0]
    
    return JsonResponse({"potential_cloud": potential_cloud}, safe=False)


def delete_potential_cloud(request):
    id = request.GET.get('id')
    potential_cloud = PotentialCloud.objects.get(id=id)

    potential_cloud.delete()
    return HttpResponseRedirect("/cloud-overview")


def get_edit_potential_cloud_modal(request):
    print("get_edit")
    id = request.GET.get('id')
    potential_cloud = PotentialCloud.objects.get(id=id)
    context = {
        "cloud": potential_cloud
        }
    return render(request, "cloudoverview/edit-potential-cloud-modal.html", context)


def edit_potential_cloud(request):
    changes = {}
    id = request.POST.get("id")
    changes["cloud_name"] = request.POST.get("cloud_name") if request.POST.get("cloud_name") else None
    changes["version"] = request.POST.get("version") if request.POST.get("version") else None
    changes["total_cpu"] = request.POST.get("cpu") if request.POST.get("cpu") else None
    changes["cpu_contention"] = request.POST.get("cpu_contention") if request.POST.get("cpu_contention") else None
    changes["ram_contention"] = request.POST.get("ram_contention") if request.POST.get("ram_contention") else None
    changes["total_ram"] = request.POST.get("ram") if request.POST.get("ram") else None
    changes["storage"]= request.POST.get("storage") if request.POST.get("storage") else None
    changes["number_of_hosts"] = request.POST.get("number_of_hosts") if request.POST.get("number_of_hosts") else None
    changes["provisioning"] = request.POST.get("provisioning") if request.POST.get("provisioning") else None

    response = {}
    potential_cloud = PotentialCloud.objects.get(id=id)
    for key in changes:
        if changes[key]:
            try:
                setattr(potential_cloud, key, changes[key])
            except Exception as e:
                response[key] = str(e)

    potential_cloud.save()
    if not response:
        response["Message"] = "Success"


    return HttpResponseRedirect("/cloud-overview")

cloudoverview/templates/cloudoverview/cloud-overview.html
{% extends 'utils/main.html' %}

{% load mathfilters %}
{% load cloud_stats_tags %}
{% block content %}
	<div class="modal fade" tabindex="-1" role="dialog" id="modal" style="z-index:10000">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content"></div>
	  </div>
	</div>
	<section class="content" ng-show="!transitioning" style="">
		<section class="container">
			<ui-view>
			<section>
				<div class="page-header">
					<h1>Clouds Overview</h1>
				</div>
				<div>	
					<table class="table table-striped table-condensed table-hover dataTable no-footer">
						<thead>
							<tr>
								<th>Cloud</th>
								<th>Version</th>
								<th>Health Status</th>
								<!--
								<th>CPU</th>
								<th>RAM</th>
								<th>Storage</th>
								-->
								<th>No. of Hosts</th>
								<th>Tot. Rem. CPU</th>
								<th>Tot. Rem. RAM</th>
								<th>Avg Rem. CPU Per Host</th>
								<th>Avg Rem. RAM Per Host</th>
								<th>Volumes Used</th>
								<th>Provisioning</th>
								<th>IP's</th>
								<!--
								<th>Ext.NFS</th>
								-->
							</tr>
						</thead>
						<tbody>
							{% for cloud in clouds %} {% if not cloud.shared_cloud %}
							<tr>
								<td>{{ cloud.cloud_name }}</td>
								<td>{% if not cloud.openstack_version %} - {% else %} {{ cloud.openstack_version }} {% endif %}</td>
								<td>{% if cloud.cloud_status == "OK" %} <span class="glyphicon glyphicon-ok-sign" style="color:green"></span> {% elif cloud.cloud_status == "Warning" %} <span class="glyphicon glyphicon-remove-sign" style="color:red"></span> {% else %} <span class="glyphicon glyphicon-minus-sign"></span> {% endif %}</td>
								<!--
								<td>{{ cloud.cpu }} / {{ cloud.total_cpu }}</td>
								<td>{{ cloud.ram|intdiv:1000 }} / {{ cloud.total_ram|intdiv:1000 }}</td> 
								<td>{{ cloud.cinder_storage }} / {{ cloud.total_cinder_storage }}</td>
								
								<li>Disabled Hosts: {{ cloud.num_disabled_compute_nodes }}</li>
								<li>CPU Cont. Ratio: {{ cloud.cpu_ratio }}</li>
								<li>RAM Cont. Ratio: {{ cloud.ram_ratio }}</li>
								-->
								<td>{{ cloud.hosts_info.hosts_count }}</td>
								<td>{{ cloud.hosts_info.total_remaining_cpu }}</td>
								<td>{{ cloud.hosts_info.total_remaining_ram }}</td>
								<td>{{ cloud.hosts_info.avg_remaining_cpu }}</td>
								<td>{{ cloud.hosts_info.avg_remaining_ram }}</td>
								<td>
								{% with cloud_data=cloud_capacity_data.cloud_info.redhat|get_item:cloud.cloud_name|get_item:cloud.cloud_name %}
								{{ cloud_data.total_volumes_used }} / {{ cloud_data.max_cloud_volume }}
								{% endwith %}
								</td>
								<td>{% if cloud.thick_provisioning %} Thick {% else %} Thin {% endif %}</td>
								<td>-</td>
							</tr>
							{% endif %} {% endfor %}
						</tbody>
					</table>
				</div>
			</section>
			
			<section>
				<div class="page-header">
					<h1>Potential Clouds</h1>
				</div>
				<a id="create-potential-cloud" type="button" name="create-potential-cloud" class="btn btn-sm btn-success" href="{% url 'cloudoverview:create-potential-cloud' %}">Create New Provisional Cloud</a>
				<div>
					<table class="table table-striped table-condensed table-hover dataTable no-footer">
						<thead>
							<tr>
								<th>Cloud</th>
								<th>Version</th>
								<th>CPU</th>
								<th>RAM</th>
								<th>Storage</th>
								<th>No. of Hosts</th>
								<th>Provisioning</th>
								<th>Actions</th>
							</tr>
						</thead>
							
						<tbody>
							{% for cloud in potential_clouds %}
							<tr>
								<td>{{ cloud.cloud_name }}</td>
								<td>{{ cloud.version }}</td>
								<td>{{ cloud.total_cpu }}</td>
								<td>{{ cloud.total_ram }}</td> 
								<td>{{ cloud.storage }}</td>
								<td>{{ cloud.number_of_hosts }}</td>
								<td>{{ cloud.provisioning }}</td>
								<td>
									<a type="button" id="edit-button-{{cloud.id}}" class="edit-button btn btn-sm btn-primary" data-toggle="modal" data-target="#cloud-edit" href="{% url 'cloudoverview:edit-potential-cloud-modal' %}?id={{cloud.id}}">Edit</a>&nbsp;
									<a type="button" class="delete-button-{{cloud.id}} btn btn-sm btn-danger" href="{% url 'cloudoverview:delete-potential-cloud' %}?id={{cloud.id}}">Delete</a>
								</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</section>
			</ui-view>
		</section>
	</section>


<!-- Cloud edit modal -->
<div class="modal fade" id="cloud-edit" role="dialog" style="z-index:10000">
  <div class="modal-dialog">
	<!-- Modal content-->
	<div class="modal-content">
	</div>
  </div>
</div>
<!-- end cloud edit modal -->

{% endblock content %}

{% block extrascripts %}

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<style type="text/css">
svg > g > g:last-child { pointer-events: none }
</style>

<script type="text/javascript">

</script>

{% endblock extrascripts %}

cloudoverview/templates/cloudoverview/create_potential_cloud.html
{% extends 'utils/main.html' %} {% block content %}

<section class="content" style>
<section class="container">
	<section ui-view="" class="" style="">
		<ui-view class="" style="">
		<section>
			<div class="page-header">
				<h1>Creating Potential Cloud</h1>
			</div>
			<div class="container">
				<form method="post" action="">
					{% csrf_token %}
						{% for field in form %}
						<div class="form-group{% if field.errors %} invalid{% endif %}">
							<label for="{{ field.id_for_label }}">{{ field.label }}</label> 
							{{field }} 
							{% for error in field.errors %}
							<p class="help-block">{{ error }}</p>
							{% endfor %}
						</div>
						{% endfor %}
				
					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						<button type="submit" class="btn btn-primary">Create</button>
					</div>
				</form>
			</div>
		</section>
		</ui-view>
	</section>

</section>
</section>

{% endblock content %}

cloudoverview/templates/cloudoverview/edit-potential-cloud-modal.html
{% block page_content %}
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h4 class="modal-title">Edit Potential Cloud</h4>
</div>
<div id="edit-potential-cloud-modal-body" class='modal-body'>

<div class="content_page_only" role="main">
    <div class="">
      <div class="clearfix"></div>
      <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h3>{{cloud.cloud_name}}</h3>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                  <li><a class="close-link"><i class="fa fa-close"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>
              <div class="x_content">

              <div class="modal-container">



             <form class="form-horizontal" action="{% url 'cloudoverview:edit-potential-cloud' %}" method="post">
                 {% csrf_token %}
                <div class="form-group">
                  <label class="control-label col-md-4 col-sm-4 col-xs-12" for="version">Name<span class="required">*</span>
                  </label>
                  <div class="col-md-4 col-sm-4 col-xs-12">
                    <input type="text" id="cloud_name" name="cloud_name" required="required" value={{cloud.cloud_name}} class="form-control col-md-7 col-xs-12">
                  </div>
                </div><div class="form-group">
                  <label class="control-label col-md-4 col-sm-4 col-xs-12" for="version">Version<span class="required">*</span>
                  </label>
                  <div class="col-md-4 col-sm-4 col-xs-12">
                    <input type="text" id="version" name="version" required="required" value={{cloud.version}} class="form-control col-md-7 col-xs-12">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-4 col-sm-4 col-xs-12" for="cpu">CPU <span class="required">*</span>
                  </label>
                  <div class="col-md-4 col-sm-4 col-xs-12">
                    <input type="number" id="cpu" name="cpu" required="required" value={{cloud.total_cpu}} class="form-control col-md-7 col-xs-12">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-4 col-sm-4 col-xs-12" for="cpu_contention">CPU Contention<span class="required">*</span>
                  </label>
                  <div class="col-md-4 col-sm-4 col-xs-12">
                    <input type="number" id="cpu_contention" name="cpu_contention" required="required" value={{cloud.cpu_contention}} class="form-control col-md-7 col-xs-12">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-4 col-sm-4 col-xs-12" for="ram">RAM<span class="required">*</span>
                  </label>
                  <div class="col-md-4 col-sm-4 col-xs-12">
                    <input type="number" id="ram" name="ram" name="ram" required="required" value={{cloud.total_ram}} class="form-control col-md-7 col-xs-12">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-4 col-sm-4 col-xs-12" for="ram">RAM Contention<span class="required">*</span>
                  </label>
                  <div class="col-md-4 col-sm-4 col-xs-12">
                    <input type="number" id="ram_contention" name="ram_contention" name="ram" required="required" value={{cloud.ram_contention}} class="form-control col-md-7 col-xs-12">
                  </div>
                </div>
                <div class="form-group">
                      <label class="control-label col-md-4 col-sm-4 col-xs-12" for="storage">Storage<span class="required">*</span>
                      </label>
                      <div class="col-md-4 col-sm-4 col-xs-12">
                        <input type="number" id="storage" name="storage" required="required" value={{cloud.storage}} class="form-control col-md-7 col-xs-12">
                      </div>
                </div>
                 <div class="form-group">
                      <label class="control-label col-md-4 col-sm-4 col-xs-12" for="storage">No. of Hosts<span class="required">*</span>
                      </label>
                      <div class="col-md-4 col-sm-4 col-xs-12">
                        <input type="number" id="number_of_hosts" name="number_of_hosts" required="required" value={{cloud.number_of_hosts}} class="form-control col-md-7 col-xs-12">
                      </div>
                </div>
                 <div class="form-group">
                      <label class="control-label col-md-4 col-sm-4 col-xs-12" for="storage">Provisioning<span class="required">*</span>
                      </label>
                      <div class="col-md-4 col-sm-4 col-xs-12">
                        <input type="text" id="provisioning" name="provisioning" required="required" value={{cloud.provisioning}} class="form-control col-md-7 col-xs-12">
                      </div>
                </div>

                <input type="hidden" name="id" value={{cloud.id}} />

                <div class="form-group">
                <div class="col-sm-offset-4 col-sm-6">
                  <button id="cloud-edit-confirm-button" type="submit" class="btn btn-primary btn-sm">Save Changes</button>
                  <button id="cloud-edit-cancel-button" type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
                </div>
              </div>
              </form>
              </div>


              </div>
              </div>
            </div>
          </div>
        </div>

    </div>
</div>
{% endblock %}
<!-- /page content -->