blog/urls.py
from django.urls import path
from django.conf.urls import url,include

from . import views

app_name='blog'

urlpatterns=[
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('user-auth/', views.user_auth, name='user-auth'),
    path('user-auth/blog/success/', views.success, name='success'),
]

cloudoverview/urls.py
from django.urls import path

from . import views

app_name='cloudoverview'

urlpatterns=[
    path('cloud-overview/', views.cloud_overview, name='cloud-overview'),
    path('create-potential-cloud/', views.PotentialCloudCreateView.as_view(), name='create-potential-cloud'), 
    path('get-potential-cloud-api/', views.get_potential_cloud_api, name='get-potential-cloud-api'), 
    path('delete-potential-cloud/', views.delete_potential_cloud, name='delete-potential-cloud'),
    path('edit-potential-cloud/', views.edit_potential_cloud, name='edit-potential-cloud'),
    path('edit-potential-cloud-modal/', views.get_edit_potential_cloud_modal, name='edit-potential-cloud-modal'),
]

okta/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('utils.urls',namespace='utils')),
    path('',include('demandmanagement.urls',namespace='demandmanagement')),
    path('',include('forecasts.urls',namespace='forecasts')),
    path('',include('cloudoverview.urls',namespace='cloud-overview')),
    path('',include('cloudstats.urls',namespace='cloud-stats')),
    path('',include('resourceaccommodator.urls',namespace='resourceaccommodator')),
]

resourceaccommodator/urls.py
from django.urls import path
from django.conf.urls import url,include

from . import views

app_name='resourceaccommodator'

urlpatterns=[
    path('resource-accommodator/', views.resource_accommodator, name='resource-accommodator'),
    path('resourceaccommodator/cloud-calculator', views.cloud_calculator, name='cloud-calculator'),
    path('get-orderable-item-api/', views.get_orderable_item_api, name='get-orderable-item-api'),
    path('get-all-orderable-items-api', views.get_all_orderable_items_api, name='get-all-orderable-items-api'),
    path('get-all-orderable-items-dtt-api', views.get_all_orderable_items_dtt_api, name='get-all-orderable-items-dtt-api'),
    path('test', views.test, name='test'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.

class Post(models.Model):


    STATUS_CHOICES=(
        ('draft','Draft'),
        ('published','Published'),
    )

    title=models.CharField(max_length=250)
    slug=models.SlugField(max_length=250,unique_for_date='publish')
    author=models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog1_posts')

    body=models.TextField()
    publish=models.DateTimeField(default=timezone.now)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    status=models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')


    def get_absolute_url(self):
        return reverse('blog:post_detail',
            args=[self.publish.year,
                  self.publish.month,
                  self.publish.day,
                  self.slug])


    class Meta: #metadata to sort posts in ascending order
        ordering=('-publish',)

    def __str__(self):
        return self.title


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')



class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments1')
    name=models.CharField(max_length=80)
    email=models.EmailField()
    body=models.TextField()
    created=models.DateTimeField(default=timezone.now)
    updated=models.DateTimeField(auto_now_add=True)
    active=models.BooleanField(default=True)

    class Meta:
        ordering=('created',)

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

        

blog/forms.py
from django import forms
from .models import Comment



class SearchForm(forms.Form):
    query=forms.CharField()



class EmailPostForm(forms.Form): #form for sending E-mail
    name=forms.CharField(max_length=25)
    email=forms.EmailField(max_length=80)
    to=forms.EmailField(max_length=80)
    comment=forms.CharField(required=False,
            widget=forms.Textarea)


class CommentForm(forms.ModelForm):
         # form form making comments to posts
    class Meta:
        model=Comment
        fields=('name','email','body')

blog/views.py
from __future__ import unicode_literals
from django.shortcuts import render,redirect,get_object_or_404
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from .models import Post,Comment
from django.views.generic import ListView
from .forms import EmailPostForm,CommentForm,SearchForm
from taggit.models import Tag
from django.db.models import Count
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseBadRequest
from django.contrib import auth
from django.contrib.auth import authenticate,login
import copy
import json, copy, datetime

# Create your views here.
@csrf_exempt
def login(request):
    next = request.GET.get('next')
    if next is not None:
        context = {"next" : next}
    else:
        context = {"next" : "blog/success/"}
    return render(request,'blog/login.html', context)

@csrf_exempt
def user_auth(request):
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    next = request.POST.get('next', '')
    if next in [ None, ""]:
        next = "blog/success/"
    user = auth.authenticate(request, username=username, password=password)
    context = {}
    #context['username'] = username
    if user is not None:
        auth.login(request, user)
        return redirect(next)
    else:
        # stay on login page so user can re-try
        context["result"] = "Your username/password appears to be invalid. Please try again"
        return render(request, "blog/login.html", context)

@csrf_exempt
def logout(request):
    auth.logout(request)
    next = request.POST.get('next', '')
    if next in [ None, ""]:
        next = "/"
    return redirect(next)

@csrf_exempt
def success(request):
    return render(request, "blog/success.html")

blog/templates/blog/_header.html
{% load static %}

<!-- Header -->
<header header-view class="navbar navbar-fixed-top navbar-inverse"
	ng-show="navbarActive">
	<div class="container" ng-controller="HeaderController as vm">
		<div class="navbar-header">
			<button id="navbar-toggle" class="navbar-toggle" type="button"
				ng-click="vm.navbarToggle()">
				<span class="sr-only">Toggle navigation</span> <span
					class="icon-bar"></span> <span class="icon-bar"></span> <span
					class="icon-bar"></span>
			</button>
			<a us-sref="home" class="navbar-brand" href="/"> OKTA </a>
		</div>
		<nav class="navbar-collapse collapse" uib-collapse="!vm.isCollapsed"
			role="navigation" style="height: 0px;">
			<ul class="nav navbar-nav"
				ng-if="vm.menu.shouldRender(vm.authetication.user);">
				<li ng-repeat="item in vm.menu.items | orderBy: 'position'"
					ng-if="item.shouldRender(vm.authetication.user);"
					ng-switch="item.type"
					ng-class="{ dropdown: item.type === 'dropdown' }"
					ui-sref-active="active" class
					uib-dropdown="item.type === 'dropdown'"><a ng-switch-default
					ui-sref="cloudbreakdown" ng-click="vm.navbarToggle()"
					ng-bind="item.title" href="/cloudbreakdown">Clouds Overview</a>
				<li ng-repeat="item in vm.menu.items | orderBy: 'position'"
					ng-if="item.shouldRender(vm.authetication.user);"
					ng-switch="item.type"
					ng-class="{ dropdown: item.type === 'dropdown' }"
					ui-sref-active="active" class
					uib-dropdown="item.type === 'dropdown'"><a ng-switch-default
					ui-sref="Demand Management Overview" ng-click="vm.navbarToggle()"
					ng-bind="item.title" href="/demandmanagementoverview">Demand
						Management Overview</a>
				<li ng-repeat="item in vm.menu.items | orderBy: 'position'"
					ng-if="item.shouldRender(vm.authetication.user);"
					ng-switch="item.type"
					ng-class="{ dropdown: item.type === 'dropdown' }"
					ui-sref-active="active" class
					uib-dropdown="item.type === 'dropdown'"><a ng-switch-default
					ui-sref="Cloud Planner" ng-click="vm.navbarToggle()"
					ng-bind="item.title" href="/cloudplanner">Cloud Planner</a>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li><a date-toggle="tooltip" title="Version" target="_blank"
					href=""> <span>1.0.1</span>
				</a></li>
				<li>
					<div class="ebSystemBarComponent-body"></div>
				</li> {% if request.user.is_authenticated %}
				<li uib-dropdown style="cursor: pointer;" class="dropdown open">
					<a id="user-username" class="dropdown-toggle"
					data-toggle="dropdown" uib-dropdown-toggle aria-haspopup="true"
					aria-expanded="true"> <span class="ldap-username">{{ request.user.username }}</span>
				</a>
				</li> {% endif %}
				<li>
					<div class="ebSystemBarComponent-body"></div>
				</li>
				<li uib-dropdown style="cursor: pointer" class="dropdown"><a
					class="dropdown-toggle" uib-dropdown-toggle aria-haspopup="true"
					aria-expanded="false"> <span class="ebIcon ebIcon_help"></span>
						Help <b class="caret"></b>
				</a>
					<ul class="dropdown-menu" role="menu">
						<li><a href="/helpdocs" target="_blank">Help Documentation</a></li>
						<li><a href="/apidocs" target="_blank">API Documentation</a></li>
					</ul>
				</li>
			</ul>
		</nav>
	</div>
</header>
<!-- End Header -->

blog/templates/blog/base.html
{%load static%}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Django3 Blog App</title>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
  </head>
  <body class ng-controller="HeaderController">
    <header header-view class="navbar navbar-fixed-top navbar-inverse" ng-show="navbarActive">
	<div class="container" ng-controller="HeaderController as vm">
	 <div class="navbar-header">
	  <button id="navbar-toggle" class="navbar-toggle" type="button" ng-click="vm.navbarToggle()">
	   <span class="sr-only">Toggle navigation</span>
	   <span class="icon-bar"></span>
	   <span class="icon-bar"></span>
           <span class="icon-bar"></span>
          </button>
	  <a us-sref="home" class="navbar-brand" href="/">
		OKTA
	  </a>
	</div>
	<nav class="navbar-collapse collapse" uib-collapse="!vm.isCollapsed" role="navigation" style="height: 0px;">
	<ul class="nav navbar-nav" ng-if="vm.menu.shouldRender(vm.authetication.user);">
	<li ng-repeat="item in vm.menu.items | orderBy: 'position'" ng-if="item.shouldRender(vm.authetication.user);" ng-switch="item.type" ng-class="{ dropdown: item.type === 'dropdown' }" ui-sref-active="active" class uib-dropdown="item.type === 'dropdown'">
	<a ng-switch-default ui-sref="cloudbreakdown" ng-click="vm.navbarToggle()" ng-bind="item.title" href="/cloudbreakdown">Cloud Breakdown</a>
        <li ng-repeat="item in vm.menu.items | orderBy: 'position'" ng-if="item.shouldRender(vm.authetication.user);" ng-switch="item.type" ng-class="{ dropdown: item.type === 'dropdown' }" ui-sref-active="active" class uib-dropdown="item.type === 'dropdown'">
        <a ng-switch-default ui-sref="Demand Management Overview" ng-click="vm.navbarToggle()" ng-bind="item.title" href="/demandmanagementoverview">Demand Management Overview</a>
	<li ng-repeat="item in vm.menu.items | orderBy: 'position'" ng-if="item.shouldRender(vm.authetication.user);" ng-switch="item.type" ng-class="{ dropdown: item.type === 'dropdown' }" ui-sref-active="active" class uib-dropdown="item.type === 'dropdown'">
        <a ng-switch-default ui-sref="Cloud Planner" ng-click="vm.navbarToggle()" ng-bind="item.title" href="/cloudplanner">Cloud Planner</a>
	</ul>
	<ul class="nav navbar-nav navbar-right">
	<li>
	<a date-toggle="tooltip" title="Version" ng-href="" target="_blank" href="">
	<span ng_bind="vm.version">1.0.1</span>
	</a>
	</li>
	<li>
	<div class="ebSystemBarComponent-body"></div>
	</li>
	<li date-toggle="tooltip" title="Login" ng-hide="vm.authentication.user" class="ebIcon ebIcon_login ng-hide" ui-sref="authentication.signin" style="cursor: pointer" href="/authentication/signin">
	</li>
	<li uib-dropdown ng-show="vm.authentication.user" style="cursor: pointer;" class="dropdown">
	<a id="user-username" class="dropdown-toggle" uib-dropdown-toggle aria-haspopup="true" aria-expanded="false">
	<span ng_bind="vm.authentication.user.displayName">Alan Kennedy</span>
	</a>
	</li>
	<li>
        <div class="ebSystemBarComponent-body"></div>
        </li>
	<li uib-dropdown style="cursor: pointer" class="dropdown">
	<a class="dropdown-toggle" uib-dropdown-toggle aria-haspopup="true" aria-expanded="false">
	<span class="ebIcon ebIcon_help"></span>
	Help
	<b class="caret"></b>
	</a>	
	<ul class="dropdown-menu" role="menu">
	<li>
	<a href="/helpdocs" target="_blank">Help Documentation</a>
	</li>
	<li>
        <a href="/apidocs" target="_blank">Api Documentation</a>
        </li>
	</ul>
	</li>
	</ul>
	</nav>
	</div>
	</header>
	<section class="content" ng-show="!transitioning" style>
	<section class="container">
	<section ui-view class style>
	<section>
	<div class="home-page-welcome">
	<h1> Welcome to OKTA</h1>
	</div>
	<br>
	</section>
	</section>
	</section>
	</section>
	<br>
	<div class="eaLogin">
	 <div class="eaLogin-inner">
	  <div class="eaLogin-ericssonLogo"></div>
	   <div class="eaLogin-body eaLogin-login" style="disaply; block;">
	    <div class="eaLoginTitle">OKTA original</div>
	    <form name=vm.userForm" ng-submit="vm.signin()" ng-class="{ 'has-error': vm.userForm.username.$invalid || vm.userForm.password.$invalid, 'has-success': vm.userForm.username.$valid && vm.userForm.password.$valid}}" novalidate autocomplete="off" class="ng-dirty ng-valid-parse" ng-valid ng-valid-required has success style>
	     <div class="eaLogin-inputWrap">
	      <input type="text" id="username" name="username" class="ebInput eb_wMargin eaLogin-loginUsername ng-not-empty ng-dirty ng-valid-parse ng-valid ng-valid-required ng-touched" ng-model="vm.credentials.username" placeholder="Username" lowercase required style="text-transform: lowercase;">
              <input type="password" id="password" name="password" class="ebInput eb_wMargin eaLogin-loginPassword ng-not-empty ng-dirty ng-valid-parse ng-valid ng-valid-required ng-touched" ng-model="vm.credentials.password" placeholder="Password" required style>
	      <button type="submit" class="ebBtn eaLogin-formButton" ng-disabled="!vm.userForm.$valid">
	      <i class="ebIcon ebIcon_rightArrow"></i>
	      </button>
	      <span class="help-block ng-inactive" ng-messages="vm.userForm.$dirty && vm.userForm.$error" style>
	      </span>
	      </div>
	      </form>
	     </div>
	     <p class="eaLogin-copy"><span>&#169;</span> Ericsson Enterprise AB, 2021. All rights reserved.</p>
	  </div>
	 </div>
	</div> 
	<!--
	<div id="content">
        {% block content%}
        {% endblock content%}
      </div>
      <div id="sidebar">
        <h2>My Blog</h2>
        <p>This is my blog.</p>
      </div>-->
  </body>
</html>

blog/templates/blog/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Fav Icon-->
	<link href="/static/blog/img/favicon.ico" rel="icon" type="image/x-icon">
    <title>OKTA</title>


    <!-- Bootstrap -->
    <link href="{% static "gentelella/vendors/bootstrap/dist/css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static "gentelella/vendors/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static "gentelella/vendors/nprogress/nprogress.css" %}" rel="stylesheet">
    <!-- Animate.css -->
    <link href="{% static "gentelella/vendors/animate.css/animate.css" %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static "gentelella/build/css/custom.min.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/blog/style.css' %}">
  </head>
  
  <body class>
    <header header-view class="navbar navbar-fixed-top navbar-inverse">
        <div class="container">
         <div class="navbar-header">
          <button id="navbar-toggle" class="navbar-toggle" type="button">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
          </button>
          <a ui-sref="home" class="navbar-brand" href="/"> 
                OKTA
          </a>
        </div>
        <nav class="navbar-collapse collapse" uib-collapse="!vm.isCollapsed" role="navigation" style="height: 0px;">
        {% if request.user.is_authenticated %}
        <ul class="nav navbar-nav">
        <li>
        <a ui-sref="cloudbreakdown" href="/cloudbreakdown">Cloud Breakdown</a>
        <li>
        <a ui-sref="Demand Management Overview"href="/demandmanagementoverview">Demand Management Overview</a>
        <li>
        <a ui-sref="Resource Accommodator" "href="/resource-accommodator">Resource Accommodator</a>
        </ul>
        <ul class="nav navbar-nav navbar-right">
        <li>
        <a date-toggle="tooltip" title="Version" target="_blank" href="">
        <span>1.0.1</span>
        </a>
        </li>
        <li>
        <div class="ebSystemBarComponent-body"></div>
        </li>
        <li uib-dropdown style="cursor: pointer;" class="dropdown">
        <a id="user-username" class="dropdown-toggle" uib-dropdown-toggle aria-haspopup="true" aria-expanded="false">
        <span>Login</span>
        </a>
        </li>
        <li>
        <div class="ebSystemBarComponent-body"></div>
        </li>
        <li uib-dropdown style="cursor: pointer" class="dropdown">
        <a class="dropdown-toggle" uib-dropdown-toggle aria-haspopup="true" aria-expanded="false">
        <span class="ebIcon ebIcon_help"></span>
        Help
        <b class="caret"></b>
        </a>
        <ul class="dropdown-menu" role="menu">
        <li>
        <a href="/helpdocs" target="_blank">Help Documentation</a>
        </li>
        <li>
        <a href="/apidocs" target="_blank">Api Documentation</a>
        </li>
        </ul>
        </li>
        </ul>
        {% endif %}
        </nav>
        </div>
        </header>
        
        <section class="content" ng-show="!transitioning" style>
        <section class="container">
        <section ui-view class style>
        <section>
        <div class="home-page-welcome">
        <h1> Welcome to OKTA</h1>
        </div>
        <br>
        </section>
        </section>
        </section>
        </section>
        <br>
        <div class="eaLogin">
         <div class="eaLogin-inner">
          <div class="eaLogin-ericssonLogo"></div>
           <div class="eaLogin-body eaLogin-login" style="display; block;">
            <div class="eaLoginTitle">OKTA</div>
               <form  action="{% url 'blog:user-auth' %}" method="post">
                <div class="eaLogin-inputWrap">
              <input type="text" id="username" name="username" class="ebInput eb_wMargin eaLogin-loginUsername" placeholder="username" required="" />
              <input type="password" id="password" name="password" class="ebInput eb_wMargin eaLogin-loginUsername" placeholder="password" required="" />
              <input type="hidden" value={{next}} name="next" />
              <button type="submit" class="ebBtn eaLogin-formButton">
              <i class="ebIcon ebIcon_rightArrow"></i>
              </button>
              </div>
              <!--{% if result %}
                <div class="ui-notification error clickable" style="bottom: 20px; right: 10px;">
                  <i class="glyphicon glyphicon-remove"></i>
                  <div class="message">{{result}}</div>
                </div>
              {% endif %}
              <br>-->

              </form>
             </div>
             <p class="eaLogin-copy"><span>&#169;</span> Ericsson Enterprise AB, 2021. All rights reserved.</p>
          </div>
         </div>

                {% if result %}
                <div class="ui-notification error clickable" style="bottom: 20px; right: 10px;">
                  <i class="glyphicon glyphicon-remove"></i>
                  <div class="message">{{result}}</div>
                </div>
              {% endif %}

  </body>

</html>

blog/templates/blog/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

    {% block stylesheets %}
    	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
		<link rel="stylesheet" href="{% static 'blog/style.css' %}">
    {% endblock stylesheets %}

    <title>Okta</title>
  </head>

  <body class ng-controller="HeaderController">

    <!-- Includes -->
    {% include "blog/_header.html" %}

    {% block content %}{% endblock content %}

    <!-- JavaScript -->
    {% block scripts %}
      	<!-- jQuery library -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
		<script src="{% static 'blog/js/jquery.bootstrap.modal.forms.js' %}"></script>
    {% endblock scripts %}

    {% block extrascripts %}{% endblock extrascripts %}

  </body>

</html>

blog/templates/blog/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
          <a href="?page={{ page.previous_page_number }}">Previous</a>
          {% endif %}
          <span class="current">
          Page {{ page.number }} of {{ page.paginator.num_pages }}.
          </span>
          {% if page.has_next %}
          <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
  </span>
</div>

blog/templates/blog/post-search.html
{% extends "blog/base.html" %}

{% block title %}Search{% endblock %}
{% block content %}
{% if query %}
<h1>Posts containing "{{ query }}"</h1>
<h3>
{% with results.count as total_results %}
    Found {{ total_results }} result{{ total_results|pluralize }}
{% endwith %}
</h3>
{% for post in results %}
    <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
    {{ post.body|truncatewords_html:5 }}
    {% empty %}
    <p>There are no results for your query.</p>
{% endfor %}
<p><a href="{% url 'blog:post_search' %}">Search again</a></p>
{% else %}
    <h1>Search for posts</h1>
    <form method="get">
    {{ form.as_p }}
    <input type="submit" value="Search">
    </form>
{% endif %}
{% endblock %}

blog/templates/blog/success.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>OKTA</title>


    <!-- Bootstrap -->
    <link href="{% static "gentelella/vendors/bootstrap/dist/css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static "gentelella/vendors/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static "gentelella/vendors/nprogress/nprogress.css" %}" rel="stylesheet">
    <!-- Animate.css -->
    <link href="{% static "gentelella/vendors/animate.css/animate.css" %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static "gentelella/build/css/custom.min.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
  </head>
  
  <body class>
    <header header-view class="navbar navbar-fixed-top navbar-inverse">
        <div class="container">
         <div class="navbar-header">
          <button id="navbar-toggle" class="navbar-toggle" type="button">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
          </button>
          <a us-sref="home" class="navbar-brand" href="/">
                OKTA
          </a>
        </div>
        <nav class="navbar-collapse collapse" uib-collapse="!vm.isCollapsed" role="navigation" style="height: 0px;">
        {% if request.user.is_authenticated %}
        <ul class="nav navbar-nav">
        <li>
        <a ui-sref="cloudbreakdown" href="/cloudbreakdown">Cloud Breakdown</a>
        <li>
        <a ui-sref="Demand Management Overview"href="/demandmanagementoverview">Demand Management Overview</a>
        <li>
        <a ui-sref="Resource Accommodator"href="/resource-accommodator">Resource Accommodator</a>
        </ul>
        <ul class="nav navbar-nav navbar-right">
        <li>
        <a date-toggle="tooltip" title="Version" target="_blank" href="">
        <span>1.0.1</span>
        </a>
        </li>
        <li>
        <div class="ebSystemBarComponent-body"></div>
        </li>
        
        {% if request.user.is_authenticated %}
            <li uib-dropdown style="cursor: pointer;" class="dropdown open">
             <a id="user-username" class="dropdown-toggle" data-toggle="dropdown" uib-dropdown-toggle aria-haspopup="true" aria-expanded="true">
	    	  <span class="ldap-username">{{ request.user.username }}</span>
	    	  
	           <ul class="dropdown-menu" role="menu">
	            <li>
	            <a href="{% url 'blog:logout' %}" method="post">Logout</a>
	            </li>
	           </ul>
	         </a>
	        </li>
	    {% endif %}
        <li>
        <div class="ebSystemBarComponent-body"></div>
        </li>
        <ul class="dropdown-menu" role="menu">
	    <li>
	      <a href="{% url 'blog:logout' %}" method="post">Logout</a>
	    </li>
	    </ul>
        <!--<li uib-dropdown style="cursor: pointer" class="dropdown">
        <a class="dropdown-toggle" uib-dropdown-toggle aria-haspopup="true" aria-expanded="false">
        <span class="ebIcon ebIcon_help"></span>
        Help
        <b class="caret"></b>
        </a>
        <ul class="dropdown-menu" role="menu">
        <li>
        <a href="/helpdocs" target="_blank">Help Documentation</a>
        </li>
        <li>
        <a href="/apidocs" target="_blank">Api Documentation</a>
        </li>
        </ul>
        </li>-->
        </ul>
        {% endif %}
        </nav>
        </div>
        </header>
        
        <section class="content" ng-show="!transitioning" style>
        <section class="container">
        <section ui-view class style>
        <section>
        <div class="home-page-welcome">
        <h1> Welcome to OKTA</h1>
        </div>
        <br>
        </section>
        </section>
        </section>
        </section>
        <br>
  </body>
   
</html>