blog/urls.py
from django.urls import path
from django.conf.urls import url,include

from . import views

app_name='blog'

urlpatterns=[
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('user-auth/', views.user_auth, name='user-auth'),
    path('user-auth/blog/success/', views.success, name='success'),
]

cloudoverview/urls.py
from django.urls import path

from . import views

app_name='cloudoverview'

urlpatterns=[
    path('cloud-overview/', views.cloud_overview, name='cloud-overview'),
    path('create-potential-cloud/', views.PotentialCloudCreateView.as_view(), name='create-potential-cloud'), 
    path('get-potential-cloud-api/', views.get_potential_cloud_api, name='get-potential-cloud-api'), 
    path('delete-potential-cloud/', views.delete_potential_cloud, name='delete-potential-cloud'),
    path('edit-potential-cloud/', views.edit_potential_cloud, name='edit-potential-cloud'),
    path('edit-potential-cloud-modal/', views.get_edit_potential_cloud_modal, name='edit-potential-cloud-modal'),
]

okta/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('utils.urls',namespace='utils')),
    path('',include('demandmanagement.urls',namespace='demandmanagement')),
    path('',include('forecasts.urls',namespace='forecasts')),
    path('',include('cloudoverview.urls',namespace='cloud-overview')),
    path('',include('cloudstats.urls',namespace='cloud-stats')),
    path('',include('resourceaccommodator.urls',namespace='resourceaccommodator')),
]

utils/urls.py
from django.urls import path
from django.conf.urls import url,include

from . import views

app_name='utils'

urlpatterns=[
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('user-auth/', views.user_auth, name='user-auth'),
    path('user-auth/utils/success/', views.success, name='success'),
]

utils/views.py
from __future__ import unicode_literals
from django.shortcuts import render,redirect,get_object_or_404
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.views.generic import ListView
from taggit.models import Tag
from django.db.models import Count
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseBadRequest
from django.contrib import auth
from django.contrib.auth import authenticate,login
import copy
import json, copy, datetime

# Create your views here.
@csrf_exempt
def login(request):
    next = request.GET.get('next')
    if next is not None:
        context = {"next" : next}
    else:
        context = {"next" : "utils/success/"}
    return render(request,'utils/login.html', context)

@csrf_exempt
def user_auth(request):
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    next = request.POST.get('next', '')
    if next in [ None, ""]:
        next = "utils/success/"
    user = auth.authenticate(request, username=username, password=password)
    context = {}
    #context['username'] = username
    if user is not None:
        auth.login(request, user)
        return redirect(next)
    else:
        # stay on login page so user can re-try
        context["result"] = "Your username/password appears to be invalid. Please try again"
        return render(request, "utils/login.html", context)

@csrf_exempt
def logout(request):
    auth.logout(request)
    next = request.POST.get('next', '')
    if next in [ None, ""]:
        next = "/"
    return redirect(next)

@csrf_exempt
def success(request):
    return render(request, "utils/success.html")

utils/templates/utils/_header.html
{% load static %}

<!-- Header -->

<header header-view class="navbar navbar-fixed-top navbar-inverse"
	ng-show="navbarActive">
	<div class="container" ng-controller="HeaderController as vm">
		<div class="navbar-header">
			<button id="navbar-toggle" class="navbar-toggle" type="button"
				ng-click="vm.navbarToggle()">
				<span class="sr-only">Toggle navigation</span> <span
					class="icon-bar"></span> <span class="icon-bar"></span> <span
					class="icon-bar"></span>
			</button>
			<a ui-sref="home" class="navbar-brand" href="/"><img src="{% static 'utils/img/ericsson-logo-blue.png' %}" style="display:inline-block"> OKTA</a>
		</div>
		
		<nav class="navbar-collapse collapse" uib-collapse="!vm.isCollapsed"
			role="navigation" style="height: 0px;">
			{% if request.user.is_authenticated %}
			<ul class="nav navbar-nav">
				<li><a href="/cloud-overview">Clouds Overview</a>
				<li><a href="/cloud-stats">Cloud Stats</a>
				<li><a href="/resource-accommodator">Resource Accommodator</a>
				<li><a href="/demand-management">Demand Management</a>
				<li><a href="/forecasts">Forecasts</a>
			</ul>
			{% endif %}
			<ul class="nav navbar-nav navbar-right">
				<li><a date-toggle="tooltip" title="Version" target="_blank"
					href=""> <span></span>
					
					
				
				</a></li>
				<li>
					<div class="ebSystemBarComponent-body"></div>
				
				</li> {% if request.user.is_authenticated %}
				
				<li uib-dropdown style="cursor: pointer;" class="dropdown open">
					<a id="user-username" class="dropdown-toggle"
					data-toggle="dropdown" uib-dropdown-toggle aria-haspopup="true"
					aria-expanded="true"> <span class="ldap-username">{{ request.user.username }}</span>
				</a>
				
				</li> {% else %}
				
				<li ng-repeat="item in vm.menu.items | orderBy: 'position'"
					ng-if="item.shouldRender(vm.authetication.user);"
					ng-switch="item.type"
					ng-class="{ dropdown: item.type === 'dropdown' }"
					ui-sref-active="active" class
					uib-dropdown="item.type === 'dropdown'"><a ng-switch-default
					ui-sref="Sign in" ng-click="vm.navbarToggle()"
					ng-bind="item.title" href="/">Sign in</a>
				
				</li> {% endif %}
				
				</li> {% if request.user.is_authenticated %}
				
				<li ng-repeat="item in vm.menu.items | orderBy: 'position'"
					ng-if="item.shouldRender(vm.authetication.user);"
					ng-switch="item.type"
					ng-class="{ dropdown: item.type === 'dropdown' }"
					ui-sref-active="active" class
					uib-dropdown="item.type === 'dropdown'"><a ng-switch-default
					ui-sref="Log Out" ng-click="vm.navbarToggle()"
					ng-bind="item.title" href="/logout/">Log Out</a>
				
				</a>
				</li> {% else %}
				
				<li ng-repeat="item in vm.menu.items | orderBy: 'position'"
					ng-if="item.shouldRender(vm.authetication.user);"
					ng-switch="item.type"
					ng-class="{ dropdown: item.type === 'dropdown' }"
					ui-sref-active="active" class
					uib-dropdown="item.type === 'dropdown'"><a ng-switch-default
					ui-sref="Log Out" ng-click="vm.navbarToggle()"
					ng-bind="item.title" href="/"></a>
				
				</li> {% endif %}
					
					</ul>
				</li>
			</ul>
		</nav>
	</div>
</header>
<!-- End Header -->

utils/templates/utils/login.html
{% extends 'utils/main.html' %} {% block content %}
     
        <section class="content" ng-show="!transitioning" style>
        <section class="container">
        <section ui-view class style>
        <section>
        
        <div class="home-page-welcome">
        <h1> Welcome to OKTA</h1>
        </div>
        
        <br>
        </section>
        </section>
        </section>
        </section>
        <br>
        
        <div class="eaLogin">
         <div class="eaLogin-inner">
          <div class="eaLogin-ericssonLogo"></div>
           <div class="eaLogin-body eaLogin-login" style="display; block;">
            <div class="eaLogin-title">OKTA</div>
            	{% if request.user.is_authenticated %}
            	<h3>You are already logged in</h3>
            	{% else %}
               <form  action="{% url 'utils:user-auth' %}" method="post">
                <div class="eaLogin-inputWrap">
              <input type="text" id="username" name="username" class="ebInput eb_wMargin eaLogin-loginUsername" placeholder="username" required="" />
              
              <input type="password" id="password" name="password" class="ebInput eb_wMargin eaLogin-loginUsername" placeholder="password" required="" />
              <input type="hidden" value={{next}} name="next" />
              
              <button type="submit" class="ebBtn eaLogin-formButton">
              <i class="ebIcon ebIcon_rightArrow"></i>
              </button>
              
              </div>
              <!--{% if result %}
                <div class="ui-notification error clickable" style="bottom: 20px; right: 10px;">
                  <i class="glyphicon glyphicon-remove"></i>
                  <div class="message">{{result}}</div>
                </div>
              {% endif %}
              
              <br>-->

              </form>
             </div>
             <p class="eaLogin-copy"><span>&#169;</span> Ericsson Enterprise AB, 2021. All rights reserved.</p>
          </div>
         </div>
		{% endif %}
                {% if result %}
                <div class="ui-notification error clickable" style="bottom: 20px; right: 10px;">
                  <i class="glyphicon glyphicon-remove"></i>
                  <div class="message">{{result}}</div>
                </div>
              {% endif %}

{% endblock content %}

utils/templates/utils/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

    {% block stylesheets %}
    	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
		<link rel="stylesheet" href="{% static 'utils/style.css' %}">
    {% endblock stylesheets %}
	<link rel="icon" type="image/ico" href="{% static 'utils/img/favicon.ico' %}">
    <title>Okta</title>
  </head>

  <body class ng-controller="HeaderController">

    <!-- Includes -->
    {% include "utils/_header.html" %}

    {% block content %}{% endblock content %}

    <!-- JavaScript -->
    {% block scripts %}
      	<!-- jQuery library -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
		<script src="{% static 'utils/js/jquery.bootstrap.modal.forms.js' %}"></script>
    {% endblock scripts %}

    {% block extrascripts %}{% endblock extrascripts %}

  </body>

</html>

utils/templates/utils/success.html
{% extends 'utils/main.html' %} {% block content %}        
        <section class="content" ng-show="!transitioning" style>
        <section class="container">
        <section ui-view class style>
        <section>
        <div class="home-page-welcome">
        <h1> Welcome to OKTA</h1>
        </div>
        <br>
        </section>
        </section>
        </section>
        </section>
        <br>
{% endblock content %}